export const GET_ALL_GENRES = "GET_ALL_GENRES";

export const GET_ALL_IMAGES = "GET_ALL_IMAGES";

export const GET_ALL_MOVIES = "GET_ALL_MOVIES";

export const SET_LOADING = "SET_LOADING";
export const CLEAR_LOADING = "CLEAR_LOADING";

export const GET_REVIEWS_BY_MOVIES_ID = "GET_REVIEWS_BY_MOVIES_ID";
export const ADD_REVIEW = "ADD_REVIEW";
export const EDIT_REVIEW = "EDIT_REVIEW";